#!/usr/bin/env node
/**
 * build.js — 451-docs ローカル開発補助スクリプト
 *
 * 本番は Netlify Functions (/api/posts, /api/post) が
 * md-contents リポジトリから直接 Markdown を取得する。
 *
 * このスクリプトはローカル開発時にのみ使用する：
 *   - content/posts/*.md を読んで posts-data/{slug}.json を生成
 *   - netlify dev が Functions を実行できない環境向けのフォールバック
 *
 * 通常のローカル開発は `netlify dev` を使うこと（Functions + GitHub API を使う）。
 *
 * 使い方:
 *   node build.js            ビルド（content/posts/ → posts-data/）
 *   node build.js --watch    ウォッチモード
 */

const fs   = require('fs');
const path = require('path');
const { buildPostData } = require('./netlify/functions/_lib/frontmatter');

const CONTENT_DIR  = path.join(__dirname, 'content', 'posts');
const OUTPUT_DIR   = path.join(__dirname, 'posts-data');
const POSTS_JSON   = path.join(__dirname, 'posts.json');
const HOME_DATA_JS = path.join(__dirname, 'js', 'home-data.js');

function buildFile(filename) {
  const raw      = fs.readFileSync(path.join(CONTENT_DIR, filename), 'utf-8');
  const postData = buildPostData(filename, raw);
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
  fs.writeFileSync(
    path.join(OUTPUT_DIR, `${postData.slug}.json`),
    JSON.stringify(postData, null, 2), 'utf-8'
  );
  console.log(`  built: posts-data/${postData.slug}.json`);
  return postData;
}

function updateIndex(allPosts) {
  const sorted   = [...allPosts].sort((a, b) => b.date.localeCompare(a.date));
  const metaList = sorted.map(({ slug, title, date, description, thumbnail, category, components }) => ({
    slug, title, date, description, thumbnail, category, components,
  }));
  fs.writeFileSync(POSTS_JSON, JSON.stringify(metaList, null, 2), 'utf-8');
  console.log(`  updated: posts.json (${metaList.length} posts)`);
  const js = `// Auto-generated by build.js (local dev only) — DO NOT COMMIT\nwindow.PUBLIC_POSTS = ${JSON.stringify(metaList, null, 2)};\n`;
  fs.writeFileSync(HOME_DATA_JS, js, 'utf-8');
  console.log(`  updated: js/home-data.js (local dev fallback)`);
}

function buildAll() {
  console.log('\n▶ build.js — local dev build');
  if (!fs.existsSync(CONTENT_DIR)) {
    console.error(`  ERROR: ${CONTENT_DIR} not found.`);
    console.error('  Place .md files in content/posts/ for local dev,');
    console.error('  or use `netlify dev` to test against the live GitHub API.');
    process.exit(1);
  }
  const files = fs.readdirSync(CONTENT_DIR).filter(f => f.endsWith('.md'));
  if (files.length === 0) { console.log('  No .md files found.'); updateIndex([]); return; }
  const allPosts = files.map(buildFile);
  updateIndex(allPosts);
  console.log(`✓ Done. ${files.length} post(s) built.\n`);
}

function watchMode() {
  buildAll();
  console.log(`👀 Watching ${CONTENT_DIR} …`);
  fs.watch(CONTENT_DIR, (_, filename) => {
    if (!filename?.endsWith('.md')) return;
    console.log(`\n  change detected: ${filename}`);
    try { buildAll(); } catch (e) { console.error('  build error:', e.message); }
  });
}

const args = process.argv.slice(2);
if (args.includes('--watch')) watchMode();
else buildAll();